name: 'Terraform AWS Resource Onboarding'

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone state repo
        uses: actions/checkout@v4
        with:
          repository: savitri443/terraform-tfstate
          token: ${{ secrets.STATE_REPO_TOKEN }}
          path: state-repo

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy state file
        run: |
          mkdir -p ./terraform
          cp state-repo/terraform-aws.tfstate ./terraform/terraform-aws.tfstate || true

      - name: Backup state file
        run: |
          mkdir -p ./terraform-backup
          if [ -f ./terraform/terraform-aws.tfstate ]; then
            cp ./terraform/terraform-aws.tfstate ./terraform-backup/terraform-aws.tfstate.bak
          fi

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: ./terraform
        
      - name: Copy updated state file back
        run: |
          cp ./terraform/terraform-aws.tfstate state-repo/terraform-aws.tfstate

      - name: Commit and push state file
        run: |
          cd state-repo
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add terraform-aws.tfstate
          git commit -m "Update terraform state [skip ci]" || echo "No changes to commit"
          git push